-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pokemon2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pokemon2` ;

-- -----------------------------------------------------
-- Schema pokemon2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokemon2` DEFAULT CHARACTER SET utf8 ;
USE `pokemon2` ;

-- -----------------------------------------------------
-- Table `pokemon2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pokemon2` ;

CREATE TABLE IF NOT EXISTS `pokemon2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `power` VARCHAR(1000) NOT NULL,
  `hp` INT UNSIGNED NOT NULL,
  `stage` INT UNSIGNED NOT NULL,
  `set` VARCHAR(45) NOT NULL,
  `pic` VARCHAR(500) NULL,
  `status` VARCHAR(45) NULL,
  `notes` VARCHAR(500) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS pokeuser@localhost;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'pokeuser'@'localhost' IDENTIFIED BY 'mewtew';

GRANT SELECT, INSERT, TRIGGER ON TABLE * TO 'pokeuser'@'localhost';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE * TO 'pokeuser'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pokemon2`
-- -----------------------------------------------------
START TRANSACTION;
USE `pokemon2`;
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (1, 'Alakazam', 'Pokemon Power: Damage Swap.  As often as you like during your turn (before your attack), you may move 1 damage counter from 1 of your Poekmon to another as long as you don\'t Knock Out that Pokemon.  This power can\'t be used if Alakazam is Asleep, Confused, or Paralyzed.', 80, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/alakazam-base-set-bs-1.jpg\">Image</a>\"', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (2, 'Blastoise', 'Pokemon Power: Rain Dance.  As often as you during your turn (before you attack), you may attack 1 [W] Energy card to 1 of your [W] Pokemon.  (This doesn\'t use up your 1 Energy card attachment for the turn.)  This power can\'t be used if Blastoise is Asleep, Confused, or Paralyzed.', 100, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/blastoise-base-set-bs-2.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (3, 'Chansey', '[C][C] Scrunch: Flip a coin.  If heads, prevent all damage done to Chansey during your opponent\'s next turn.  (Any other effects of attacks still happen.)', 120, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/chansey-base-set-bs-3.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (4, 'Charizard', 'Pokemon Power: Energy Burn.  As often as you like during your turn (before your attack), you may turn all Energy attached to Charizard into [R] Energy for the rest of the turn. This power can\'t be used if Charizard is Asleep, Confused, or Paralyzed.', 120, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/charizard-base-set-bs-4.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (5, 'Clefairy', '[C] Sing: Flip a coin.  If heads, the Defending Pokemon is now Asleep.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/clefairy-base-set-bs-5.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (6, 'Gyrados', '\n[W][W][W] Dragon Rage: 50 damage.', 100, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/gyarados-base-set-bs-6.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (7, 'Hitmonchan', '\n[F] Jab: 20 damage.', 70, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/hitmonchan-base-set-bs-7.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (8, 'Machamp', '\nPokémon Power: Strikes Back\nWhenever your opponent’s attack damages Machamp (even if Machamp is Knocked Out), this power does 10 damage to the attacking Pokémon. (Don’t apply Weakness and Resistance.) This power can’t be used if Machamp is Asleep, Confused, or Paralyzed when your opponent attacks.', 100, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/machamp-base-set-bs-8.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (9, 'Magneton', 'L][L][C] Thunder Wave: 30 damage. Flip a coin. If heads, the Defendind Pokémon is now Paralyzed.', 60, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/magneton-base-set-bs-9.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (10, 'Mewtwo', '\n[P][C] Psychic: 10+ damage. Does 10 damage plus 10 more damage for each Energy card attached to the Defending Pokémon.', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/mewtwo-base-set-bs-10.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (11, 'Nidoking', '\n[G][C][C] Thrash: 30+ damage. Flip a coin. If heads, this attack does 30 damage plus 10 more damage; if tails, this attack does 30 damage and Nidoking does 10 damage to itself.', 90, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/nidoking-base-set-bs-11.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (12, 'Ninetales', '[C][C] Lure: If your opponent has any Benched Pokémon, choose 1 of them and switch it with his or her Active Pokémon.', 80, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/ninetales-base-set-bs-12.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (13, 'Poliwrath', '\n[W][W][C] Water Gun: 30+ damage. Does 30 damage plus 10 more damage for each [W] Energy attached to Poliwrath but not used to pay for this attack’s Energy cost. Extra [W] Energy after the 2nd don’t count.', 90, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/poliwrath-base-set-bs-13.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (14, 'Raichu', '\n[L][C][C] Agility: 20 damage. Flip a coin. If heads, during your opponent’s next turn, prevent all effects of attacks, including damage, done to Raichu.', 90, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/raichu-base-set-bs-14.jpg>Image</a>', 'H', '3');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (15, 'Venusaur', '\nPokémon Power: Energy Trans\nAs often as you like during your turn (before you attack), you may take 1 [G] Energy card attached to 1 of your Pokémon and attach it to a different one. This power can’t be used if Venusaur is Asleep, Confused, or Paralyzed.', 100, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/venusaur-base-set-bs-15.jpg>Image</a>', 'N', '3');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (16, 'Zapdos', '\n[L][L][L][C] Thunder: 60 damage. Flip a coin. If tails, Zapdos does 30 damage to itself.', 90, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/zapdos-base-set-bs-16.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (17, 'Beedrill', '\n[C][C][C] Twineedle: 30× damage. Flip 2 coins. This attack does 30 damage times the number of heads.', 80, 2, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/beedrill-base-set-bs-17.jpg>Image</a>', 'N', '3');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (18, 'Dragonair', '\n[C][C][C] Slam: 30× damage. Flip 2 coins. This attack does 30 damage times the number of heads.', 80, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/dragonair-base-set-bs-18.jpg>Image</a>', 'H', '4');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (19, 'Dugtrio', '\n[F][F][C] Slash: 40 damage.', 70, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/dugtrio-base-set-bs-19.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (20, 'Electabuzz', '\n[L] Thundershock: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Paralyzed.', 70, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/electabuzz-base-set-bs-20.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (21, 'Electrode', '\nPokémon Power: Buzzap\nAt any time during your turn (before your attack), you may Knock Out Electrode and attach it to 1 of your other Pokémon. If you do, choose a type of Energy. Electrode is now an Energy card (instead of a Pokémon) that provides 2 energy of that type. You can’t use this power if Electrode is Asleep, Confused, or Paralyzed.', 80, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/electrode-base-set-bs-21.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (22, 'Pidgeotto', '\n[C][C] Whirlwind: 20 damage. If your opponent has any Benched Pokémon, he or she chooses 1 of them and switches it with the Defending Pokémon. (Do the damage before switching the Pokémon.)', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pidgeotto-base-set-bs-22.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (23, 'Arcanine', '\n[R][R][C] Flamethrower: 50 damage. Discard 1 [R] Energy card attached to Arcanine in order to use this attack.', 100, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/arcanine-base-set-bs-23.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (24, 'Charmeleon', '\n[C][C][C] Slash: 30 damage.', 80, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/charmeleon-base-set-bs-24.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (25, 'Dewdong', '\n[W][W][C] Aurora Beam: 50 damage.', 80, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/dewgong-base-set-bs-25.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (26, 'Dratini', '\n[C] Pound: 10 damage.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/dratini-base-set-bs-26.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (27, 'Farfetche\'d', '[C] Leek Slap: 30 damage. Flip a coin. If tails, this attack does nothing. Either way, you can’t use this attack again as long as Farfetch’d stays in play (even putting Farfetch’d on the Bench won’t let you use it again).', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/farfetchd-base-set-bs-27.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (28, 'Growlithe', '\n[R][C] Flare: 20 damage.', 60, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/growlithe-base-set-bs-28.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (29, 'Haunter', '[P] Hypnosis: The Defending Pokémon is now Asleep.', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/haunter-base-set-bs-29.jpg>Image</a>', 'N', '3');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (30, 'Ivysaur', '[G][C][C] Vine Whip: 30 damage.', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/ivysaur-base-set-bs-30.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (31, 'Jynx', '\n[P] Doubleslap: 10× damage. Flip 2 coins. This attack does 10 damage times the number of heads.', 70, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/jynx-base-set-bs-31.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (32, 'Kadabra', '\n[P][P] Recover: Discard 1 [P] Energy card attached to Kadabra in order to use this attack. Remove all damage counters from Kadabra.', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/kadabra-base-set-bs-32.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (33, 'Kakuna', '\n[C][C] Stiffen: Flip a coin. If heads, prevent all damage done to Kakuna during your opponent’s next turn. (Any other effects of attacks still happen.)', 80, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/kakuna-base-set-bs-33.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (34, 'Machoke', '\n[F][F][C] Karate Chop: 50- damage. Does 50 damage minus 10 damage for each damage counter on Machoke.', 80, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/machoke-base-set-bs-34.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (35, 'Magikarp', '\n[C] Tackle: 10 damage.', 30, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/magikarp-base-set-bs-35.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (36, 'Magmar', '\n[R][R] Fire Punch: 30 damage.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/magmar-base-set-bs-36.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (37, 'Nidorino', '\n[G][C][C] Double Kick: 30× damage. Flip 2 coins. This attack does 30 damage times the number of heads.', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/nidorino-base-set-bs-37.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (38, 'Poliwhirl', '\n[W][W] Amnesia: Choose 1 of the Defending Pokémon’s attacks. That Pokémon can’t use that attack during your opponent’s next turn.', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/poliwhirl-base-set-bs-38.jpg>Image</a>', 'H', '3');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (39, 'Porygon', '\n[C] Conversion 1: If the Defending Pokémon has a Weakness, you may change it to a type of your choice other than Colorless.', 30, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/porygon-base-set-bs-39.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (40, 'Raticate', '\n[C] Bite: 20 damage.', 60, 1, 'Base', 'a href=https://pkmncards.com/wp-content/uploads/raticate-base-set-bs-40.jpg>Image</a>', 'N', '3');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (41, 'Seel', '\n[W] Headbutt: 10 damage.', 60, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/seel-base-set-bs-41.jpg>Image</a>', 'H', '4');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (42, 'Wartortle', '\n[W][C] Withdraw: Flip a coin. If heads, prevent all damage done to Wartortle during your opponent’s next turn. (Any other effects of attacks still happen.)', 70, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/wartortle-base-set-bs-42.jpg>Image</a>', 'N', '4');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (43, 'Abra', '\n[P] Psyshock: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Paralyzed.', 30, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/abra-base-set-bs-43.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (44, 'Bulbasaur', '\n[G][G] Leech Seed: 20 damage. Unless all damage from this attack is prevented, you may remove 1 damage counter from Bulbasaur.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/bulbasaur-base-set-bs-44.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (45, 'Caterpie', '\n[G] String Shot: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Paralyzed.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/caterpie-base-set-bs-45.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (46, 'Charmander', '\n[C] Scratch: 10 damage.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/charmander-base-set-bs-46.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (47, 'Diglett', '\n[F] Dig: 10 damage.', 30, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/diglett-base-set-bs-47.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (48, 'Doduo', '\n[C] Fury Attack: 10× damage. Flip 2 coins. This attack does 10 damage times the number of heads.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/doduo-base-set-bs-48.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (49, 'Drowzee', '[C] Pound: 10 damage.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/drowzee-base-set-bs-49.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (50, 'Gastly', '[P] Sleeping Gas: Flip a coin. If heads, the Defending Pokémon is now Asleep.', 30, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/gastly-base-set-bs-50.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (51, 'Koffing', '\n[G][G] Foul Gas: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Poisoned; if tails, it is now Confused.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/koffing-base-set-bs-51.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (52, 'Machop', '[F] Low Kick: 20 damage.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/machop-base-set-bs-52.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (53, 'Magnemite', '\n[L] Thunder Wave: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Paralyzed.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/magnemite-base-set-bs-53.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (54, 'Metapod', '\n[C][C] Stiffen: Flip a coin. If heads, prevent all damage done to Metapod during your opponent’s next turn. (Any other effects of attacks still happen.)', 70, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/metapod-base-set-bs-54.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (55, 'Nidoran Male55Base', '\n[G] Horn Hazard: 30 damage. Flip a coin. If tails, this attack does nothing.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/nidoran-male-base-set-bs-55.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (56, 'Onix', '\n[F] Rock Throw: 10 damage.', 90, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/onix-base-set-bs-56.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (57, 'Pidgey', '\nPidgey (Base Set BS 57)\nText // Rating: 17% // Proxies // Rulings // Discussion: 1\n\nBuy @ TCGplayer →\nL: $0.12M: $0.31H: $1.24\nPidgey — Colorless — 40 HP\nBasic\n\n[C][C] Whirlwind: 10 damage. If your opponent has any Benched Pokémon, he or she chooses 1 of them and switches it with the Defending Pokémon. (Do the damage before switching the Pokémon.)', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pidgey-base-set-bs-57.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (58, 'Pikachu', '\n[C] Gnaw: 10 damage.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pikachu-base-set-bs-58.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (59, 'Poliwag', '\n[W] Water Gun: 10+ damage. Does 10 damage plus 10 more damage for each [W] Energy attached to Poliwag but not used to pay for this attack’s Energy cost. Extra [W] Energy after the 2nd don’t count.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/poliwag-base-set-bs-59.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (60, 'Ponyta', '\n[C][C] Smash Kick: 20 damage.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/ponyta-base-set-bs-60.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (61, 'Rattata', '\n[C] Bite: 20 damage.', 30, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/rattata-base-set-bs-61.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (62, 'Sandshrew', '\n[F] Sand-attack: 10 damage. If the Defending Pokémon tries to attack during your opponent’s next turn, your opponent flips a coin. If tails, that attack does nothing.', 62, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/sandshrew-base-set-bs-62.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (63, 'Squirtle', '\n[W] Bubble: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Paralyzed.', 40, 0, 'Base', 'a href=https://pkmncards.com/wp-content/uploads/squirtle-base-set-bs-63.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (64, 'Starmie', '\n[W][W] Recover: Discard 1 [W] Energy card attached to Starmie in order to use this attack. Remove all damage counters from Starmie.', 60, 1, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/starmie-base-set-bs-64.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (65, 'Staryu', '\n[W] Slap: 20 damage.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/staryu-base-set-bs-65.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (66, 'Tangela', '\n[G][C] Bind: 20 damage. Flip a coin. If heads, the Defending Pokémon is now Paralyzed.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/tangela-base-set-bs-66.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (67, 'Voltorb', '[C] Tackle: 10 damage.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/voltorb-base-set-bs-67.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (68, 'Vulpix', '\n[R][R] Confuse Ray: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Confused.', 50, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/vulpix-base-set-bs-68.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (69, 'Weedle', '[G] Poison Sting: 10 damage. Flip a coin. If heads, the Defending Pokémon is now Poisoned.', 40, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/weedle-base-set-bs-69.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (70, 'Clefairy Doll', '\nPlay Clefairy Doll as if it were a Basic Pokémon. While in play, Clefairy Doll counts a a Pokémon (instead of a Trainer card). Clefairy Doll has no attacks, can’t retreat, and can’t be Asleep, Confused, Paralyzed, or Poisoned. If Clefairy Doll is Knocked Out, it doesn’t count as a Knocked Out Pokémon. At any time during your turn before your attack, you may discard Clefairy Doll.', 10, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/clefairy-doll-base-set-bs-70.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (71, 'Computer Search', '\nDiscard 2 of the other cards from you hand in order to search your deck for any card and put it into your hand. Shuffle your deck afterward.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/computer-search-base-set-bs-71.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (72, 'Devolution Spray', 'Choose 1 of your own Pokémon in play and a Stage of Evolution. Discard all Evolution cards of that Stage or higher attached to that Pokémon. That Pokémon is no longer Asleep, Confused, Paralyzed, Poisoned, or anything else that might be the result of an attack (just as if you had evolved it).', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/devolution-spray-base-set-bs-72.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (73, 'Impostor Professor Oak', '\nYour opponent shuffles his or her hand into his or her deck, then draws 7 cards.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/impostor-professor-oak-base-set-bs-73.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (74, 'Item Finder', '\nDiscard 2 of the other cards from your hand in order to put a Trainer card from your discard pile into your hand.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/item-finder-base-set-bs-74.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (75, 'Lass', '\nYou and your opponent show each other your hands, then shuffle all the Trainer cards from your hands into your decks.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/lass-base-set-bs-75.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (76, 'Pokémon Breeder', '\nPut a Stage 2 Evolution card from your hand on the matching Basic Pokémon. You can only play this card when you would be allowed to evolve that Pokémon anyway.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pokemon-breeder-base-set-bs-76.jpg>Image</a>', 'H', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (77, 'Pokémon Trader', '\nTrade 1 of the Basic Pokémon or Evolution cards in your hand for 1 of the Basic Pokémon or Evolution cards from your deck. Show both cards to your opponent. Shuffle your deck afterward.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pokemon-trader-base-set-bs-77.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (78, 'Scoop Up', 'Choose 1 of your Pokémon in play and return its Basic Pokémon card to your hand. (Discard all cards attached to that card.)', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/scoop-up-base-set-bs-78.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (79, 'Super Energy Removal', 'Discard 1 Energy card attached to 1 of your Pokémon in order to choose 1 of your opponent’s Pokémon and up to 2 Energy cards attached to it. Discard those Energy cards.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/super-energy-removal-base-set-bs-79.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (80, 'Defender', '\nAttach Defender to 1 of your Pokémon. At the end of your opponent’s next turn, discard Defender. Damage done to that Pokémon by attacks is reduced by 20 (after applying Weakness and Resistance).', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/defender-base-set-bs-80.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (81, 'Energy Retrieval', '\nTrade 1 of the other cards in your hand for up to 2 basic Energy cards from your discard pile.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/energy-retrieval-base-set-bs-81.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (82, 'Full Heal', 'Your Active Pokémon is no longer Asleep, Confused, Paralyzed, or Poisoned.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/full-heal-base-set-bs-82.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (83, 'Maintenance', '\nShuffle 2 of the other cards from your hand into your deck in order to draw a card.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/maintenance-base-set-bs-83.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (84, 'PlusPower', '\nAttach PlusPower to your Active Pokémon. At the end of your turn, discard PlusPower. If this Pokémon’s attack does damage to the Defending Pokémon (after applying Weakness and Resistance), the attack does 10 more damage to the Defending Pokémon.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pluspower-base-set-bs-84.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (85, 'Pokémon Center', '\nRemove all damage counters from all of your own Pokémon with damage counters on them, then discard all Energy cards attached to those Pokémon.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pokemon-center-base-set-bs-85.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (86, 'Pokémon Flute', '\nChoose 1 Basic Pokémon card from your opponent’s discard pile and put it onto his or her Bench. (You can’t play Pokémon Flute if your opponent’s Bench is full.)', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pokemon-flute-base-set-bs-86.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (87, 'Pokédex', '\nLook at up to 5 cards from the top of your deck and rearrange them as you like.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/pokedex-base-set-bs-87.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (88, 'Professor Oak', 'Discard your hand, then draw 7 cards.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/professor-oak-base-set-bs-88.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (89, 'Revive', '\nPut 1 Basic Pokémon card from your discard pile onto your Bench. Put damage counters on that Pokémon equal to half its HP (rounded down to the nearest 10). (You can’t play Revive if your Bench is full.)', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/revive-base-set-bs-89.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (90, 'Super Potion', '\nDiscard 1 Energy card attached to your own Pokémon in order to remove up to 4 damage counters from that Pokémon.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/super-potion-base-set-bs-90.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (91, 'Bill', '\nDraw 2 cards.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/bill-base-set-bs-91.jpg>Image</a>', 'N', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (92, 'Energy Removal', '\nChoose 1 Energy card attached to 1 of your opponent’s Pokémon and discard it.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/energy-removal-base-set-bs-92.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (93, 'Gust of Wind', 'Choose 1 of your opponent’s Benched Pokémon and switch it with his or her Active Pokémon.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/gust-of-wind-base-set-bs-93.jpg>Image</a>', 'H', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (94, 'Potion', '\nRemove up to 2 damage counters from 1 of your Pokémon.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/potion-base-set-bs-94.jpg>Image</a>', 'N', '1');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (95, 'Switch', 'Switch 1 of your own Benched Pokémon with your Active Pokémon.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/switch-base-set-bs-95.jpg>Image</a>', 'H', '0');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (96, 'Double Colorless Energy', '\nProvides [C][C] energy. Doesn’t count as a basic Energy card.', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/double-colorless-energy-base-set-bs-96.jpg>Image</a>', 'N', '2');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (97, 'Fighting Energy', 'Basic Energy', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/fighting-energy-base-set-bs-97.jpg>Image</a>', 'H', '10');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (98, 'Fire Energy', 'Basic Energy', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/fire-energy-base-set-bs-98.jpg>Image</a>', 'N', '11');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (99, 'Grass Energy', 'Basic Energy', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/grass-energy-base-set-bs-99.jpg>Image</a>', 'H', '11');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (100, 'Lightning Energy', 'Basic Energy', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/lightning-energy-base-set-bs-100.jpg>Image</a>', 'H', '12');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (101, 'Psychic Energy', 'Basic Energy', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/psychic-energy-base-set-bs-101.jpg>Image</a>', 'H', '15');
INSERT INTO `pokemon2` (`id`, `name`, `power`, `hp`, `stage`, `set`, `pic`, `status`, `notes`) VALUES (102, 'Water Energy', 'Basic Energy', 0, 0, 'Base', '<a href=https://pkmncards.com/wp-content/uploads/water-energy-base-set-bs-102.jpg>Image</a>', 'H', '8');

COMMIT;

